environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
  - java -version
  - mvn --version

build_script:
  - cp .env.example .env
  - cp flyway.properties.example flyway.properties
  - mvn clean install -DskipTests
  - mvn clean flyway:migrate -Dflyway.configFiles=flyway.properties

services:
  - mysql

# scripts that run before running test
before_test:
  # by default, all script lines are interpreted as batch
  - echo This is test script
  # to run script as a PowerShell command prepend it with ps:
  - ps: Write-Host 'This is PowerShell Script'

cache:
  - C:\maven\
  - C:\Users\appveyor\.m2