spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bpm_sbh?serverTimezone=UTC
    username: root
    password: 
  profiles.active: @activatedProperties@

server.port: 8080
cors.urls: http://localhost:8081
sendgrid.key: xxx
base.url: http://localhost:8080

spring.jpa.hibernate.use-new-id-generator-mappings: false
spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
# spring.jpa.hibernate.naming_strategy: org.hibernate.cfg.EJB3NamingStrategy
spring.jpa.properties.hibernate.jdbc.batch_size: 20
spring.jpa.properties.hibernate.order_updates: true

gcs:
  bucket: bpm-sbh
  project: bpm-sbh
  json-file: bpm-sbh.json
  client-account: sbh@bpm.iam.gserviceaccount.com
  private-key: -----BEGIN PRIVATE KEY-----\x==\n-----END PRIVATE KEY-----\n
  url: https://storage.googleapis.com
  
camunda.bpm:
  admin-user:
    id: admin
    password: admin
  webapp.index-redirect-enabled: false
  authorization.enabled: true

JWT:
  secret: 5dr9LiH^*vh$9o
  expiryDuration: 36000000