DROP TABLE IF EXISTS `project_document_generates`;
CREATE TABLE `project_document_generates` (
  `id` int PRIMARY KEY AUTO_INCREMENT,
  `name` varchar(255),
  `code` varchar(255),
  `master_certification_type_id` int(11),
  `project_document_category_id` int(11),
  `active` boolean,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `created_by` varchar(255)
);

INSERT INTO `project_document_generates` (id, code, name, master_certification_type_id, project_document_category_id, active, created_at, updated_at, created_by )
VALUES
  (1, 'proof_of_payment', 'Bukti Pembayaran DP', 1, 1, true, NOW(), NOW(), 'system'),
  (2, 'first_payment_document', 'Bukti Pembayaran Termin Pertama', 1, 2, true, NOW(), NOW(), 'system'),
  (3, 'second_payment_document', 'Bukti Pembayaran Termin Kedua', 1, 2, true, NOW(), NOW(), 'system'),
  (4, 'third_payment_document', 'Bukti Pembayaran Termin Ketiga', 1, 2, true, NOW(), NOW(), 'system'),
  (5, 'workshop_attendance_document', 'Workshop Attendance', 1, 2, true, NOW(), NOW(), 'system'),
  (6, 'workshop_report_document', 'Workshop Report', 1, 2, true, NOW(), NOW(), 'system'),
  (7, 'eligibility_statement', 'Eligibility Statement', 1, 2, true, NOW(), NOW(), 'system'),
  (8, 'agreement_letter_document', 'Agreement Letter', 1, 2, true, NOW(), NOW(), 'system'),
  (9, 'sign_post', 'Pemesanan Plang', 1, 2, true, NOW(), NOW(), 'system'),
  (10, 'approval_building_release', 'Persetujuan Pemuatan Data Gedung', 1, 2, true, NOW(), NOW(), 'system'),
  (11, 'agreement_letter_document', 'Agreement Letter', 1, 3, true, NOW(), NOW(), 'system'),
  (12, 'dr_scoring_form', 'Design Recognition Scoring Form', 1, 3, true, NOW(), NOW(), 'system'),
  (13, 'fa_scoring_form', 'Final Assessment Scoring Form', 1, 3, true, NOW(), NOW(), 'system'),
  (14, 'dr_revision_submission', 'Design Recognition Revision Submission', 1, 3, true, NOW(), NOW(), 'system'),
  (15, 'fa_revision_submission', 'Final Assessment Revision Submission', 1, 3, true, NOW(), NOW(), 'system'),
  (16, 'dr_evaluation_assessment', 'Design Recognition Evaluation Assessment', 1, 3, true, NOW(), NOW(), 'system'),
  (17, 'fa_evaluation_assessment', 'Final Assessment Evaluation Assessment', 1, 3, true, NOW(), NOW(), 'system'),
  (18, 'proof_of_payment', 'Bukti Pembayaran DP', 2, 1, true, NOW(), NOW(), 'system'),
  (19, 'first_payment_document', 'Bukti Pembayaran Termin Pertama', 2, 2, true, NOW(), NOW(), 'system'),
  (20, 'second_payment_document', 'Bukti Pembayaran Termin Kedua', 2, 2, true, NOW(), NOW(), 'system'),
  (21, 'third_payment_document', 'Bukti Pembayaran Termin Ketiga', 2, 2, true, NOW(), NOW(), 'system'),
  (22, 'workshop_attendance_document', 'Workshop Attendance', 2, 2, true, NOW(), NOW(), 'system'),
  (23, 'workshop_report_document', 'Workshop Report', 2, 2, true, NOW(), NOW(), 'system'),
  (24, 'eligibility_statement', 'Eligibility Statement', 2, 2, true, NOW(), NOW(), 'system'),
  (25, 'agreement_letter_document', 'Agreement Letter', 2, 2, true, NOW(), NOW(), 'system'),
  (26, 'sign_post', 'Pemesanan Plang', 2, 2, true, NOW(), NOW(), 'system'),
  (27, 'approval_building_release', 'Persetujuan Pemuatan Data Gedung', 2, 2, true, NOW(), NOW(), 'system'),
  (28, 'agreement_letter_document', 'Agreement Letter', 2, 2, true, NOW(), NOW(), 'system'),
  (29, 'dr_scoring_form', 'Design Recognition Scoring Form', 2, 2, true, NOW(), NOW(), 'system'),
  (30, 'fa_scoring_form', 'Final Assessment Scoring Form', 2, 2, true, NOW(), NOW(), 'system'),
  (31, 'dr_revision_submission', 'Design Recognition Revision Submission', 2, 3, true, NOW(), NOW(), 'system'),
  (32, 'fa_revision_submission', 'Final Assessment Revision Submission', 2, 3, true, NOW(), NOW(), 'system'),
  (33, 'dr_evaluation_assessment', 'Design Recognition Evaluation Assessment', 2, 3, true, NOW(), NOW(), 'system'),
  (34, 'fa_evaluation_assessment', 'Final Assessment Evaluation Assessment', 2, 3, true, NOW(), NOW(), 'system');
