DROP TABLE IF EXISTS `activity_names`;
CREATE TABLE `activity_names` (
  `id` int PRIMARY KEY AUTO_INCREMENT,
  `activity_id` varchar(255),
  `name` varchar(255),
  `master_certification_type_id` int(11),
  `active` boolean,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `created_by` varchar(255)
);

INSERT INTO `activity_names` (id, activity_id, name, master_certification_type_id, active, created_at, updated_at, created_by )
VALUES
  (1, 'fill-registration-project', 'Fill Registration Project', 1, true, NOW(), NOW(), 'system'),
  (2, 'check-registration-project', 'Check Registration Project', 1, true, NOW(), NOW(), 'system'),
  (3, 'fill-document-building', 'Fill Document Building', 1, true, NOW(), NOW(), 'system'),
  (4, 'check-document-building', 'Check Document Building', 1, true, NOW(), NOW(), 'system'),
  (5, 'agreement', 'Agreement', 1, true, NOW(), NOW(), 'system'),
  (6, 'first-payment', 'First Payment', 1, true, NOW(), NOW(), 'system'),
  (7, 'check-first-payment', 'Check First Payment', 1, true, NOW(), NOW(), 'system'),
  (8, 'workshop', 'Workshop and Cosultation', 1, true, NOW(), NOW(), 'system'),
  (9, 'second-payment', 'Second Payment', 1, true, NOW(), NOW(), 'system'),
  (10, 'check-second-payment', 'Check Second Payment', 1, true, NOW(), NOW(), 'system'),
  (11, 'design-recognition-submission', 'Design Recognition Submission', 1, true, NOW(), NOW(), 'system'),
  (12, 'design-recognition-review', 'Design Recognition Review', 1, true, NOW(), NOW(), 'system'),
  (13, 'third-payment', 'Third Payment', 1, true, NOW(), NOW(), 'system'),
  (14, 'check-third-payment', 'Check Third Payment', 1, true, NOW(), NOW(), 'system'),
  (15, 'design-recognition-evaluation-assessment', 'Design Recognition Evaluation Assessment', 1, true, NOW(), NOW(), 'system'),
  (16, 'design-recognition-trial-revision', 'Design Recognition Revision Submission', 1, true, NOW(), NOW(), 'system'),
  (17, 'design-recognition-revision-review', 'Design Recognition Revision Review', 1, true, NOW(), NOW(), 'system'),
  (18, 'design-recognition-letter', 'Design Recognition Letter', 1, true, NOW(), NOW(), 'system'),
  (19, 'final-assessment-submission', 'Final Assessment Submission', 1, true, NOW(), NOW(), 'system'),
  (20, 'final-assessment-review', 'Final Assessment Review', 1, true, NOW(), NOW(), 'system'),
  (21, 'on-site-revision-submission', 'On Site Revision', 1, true, NOW(), NOW(), 'system'),
  (22, 'on-site-verification', 'On Site Verification', 1, true, NOW(), NOW(), 'system'),
  (23, 'final-assessment-evaluation-assessment', 'Final Assessment Evaluation Assessment', 1, true, NOW(), NOW(), 'system'),
  (24, 'final-assessment-trial-revision', 'Final Assessment Revision Submission', 1, true, NOW(), NOW(), 'system'),
  (25, 'final-assessment-revision-review', 'Final Assessment Revision Review', 1, true, NOW(), NOW(), 'system'),
  (26, 'final-assessment-letter', 'Final Assessment Certificate', 1, true, NOW(), NOW(), 'system'),

  (27, 'fill-registration-project', 'Fill Registration Project', 2, true, NOW(), NOW(), 'system'),
  (28, 'check-registration-project', 'Check Registration Project', 2, true, NOW(), NOW(), 'system'),
  (29, 'fill-document-building', 'Fill Document Building', 2, true, NOW(), NOW(), 'system'),
  (30, 'check-document-building', 'Check Document Building', 2, true, NOW(), NOW(), 'system'),
  (31, 'agreement', 'Agreement', 2, true, NOW(), NOW(), 'system'),
  (32, 'first-payment', 'First Payment', 2, true, NOW(), NOW(), 'system'),
  (33, 'check-first-payment', 'Check First Payment', 2, true, NOW(), NOW(), 'system'),
  (34, 'workshop', 'Workshop and Cosultation', 2, true, NOW(), NOW(), 'system'),
  (35, 'second-payment', 'Second Payment', 2, true, NOW(), NOW(), 'system'),
  (36, 'check-second-payment', 'Check Second Payment', 2, true, NOW(), NOW(), 'system'),
  (37, 'design-recognition-submission', 'Design Recognition Submission', 2, true, NOW(), NOW(), 'system'),
  (38, 'design-recognition-review', 'Design Recognition Review', 2, true, NOW(), NOW(), 'system'),
  (39, 'third-payment', 'Third Payment', 2, true, NOW(), NOW(), 'system'),
  (40, 'check-third-payment', 'Check Third Payment', 2, true, NOW(), NOW(), 'system'),
  (41, 'design-recognition-evaluation-assessment', 'Design Recognition Evaluation Assessment', 2, true, NOW(), NOW(), 'system'),
  (42, 'design-recognition-trial-revision', 'Design Recognition Revision Submission', 2, true, NOW(), NOW(), 'system'),
  (43, 'design-recognition-revision-review', 'Design Recognition Revision Review', 2, true, NOW(), NOW(), 'system'),
  (44, 'design-recognition-letter', 'Design Recognition Letter', 2, true, NOW(), NOW(), 'system'),
  (45, 'final-assessment-submission', 'Final Assessment Submission', 2, true, NOW(), NOW(), 'system'),
  (46, 'final-assessment-review', 'Final Assessment Review', 2, true, NOW(), NOW(), 'system'),
  (47, 'on-site-revision-submission', 'On Site Revision', 2, true, NOW(), NOW(), 'system'),
  (48, 'on-site-verification', 'On Site Verification', 2, true, NOW(), NOW(), 'system'),
  (49, 'final-assessment-evaluation-assessment', 'Final Assessment Evaluation Assessment', 2, true, NOW(), NOW(), 'system'),
  (50, 'final-assessment-trial-revision', 'Final Assessment Revision Submission', 2, true, NOW(), NOW(), 'system'),
  (51, 'final-assessment-revision-review', 'Final Assessment Revision Review', 2, true, NOW(), NOW(), 'system'),
  (52, 'final-assessment-letter', 'Final Assessment Certificate', 2, true, NOW(), NOW(), 'system');
