ALTER TABLE `provinces`
ADD `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
ADD `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
ADD `created_by` VARCHAR(255);

ALTER TABLE regencies
ADD `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
ADD `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
ADD `created_by` VARCHAR(255);

ALTER TABLE districts
ADD `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
ADD `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
ADD `created_by` VARCHAR(255);

ALTER TABLE villages
ADD `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
ADD `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
ADD `created_by` VARCHAR(255);